export const clientList = [
  'Ahmad Tea',
  'Impuls Tibbiyot Instituti',
  'Milestone IS',
  'Damar',
  'Aurus Pharm',
  'Bek Ota',
  'Najot Nur Notiqlik Maktabi',
  'Merit Chemicals',
  'OXUS University',
  'MARF',
  'AQLY',
  'Zahratun Supermarket',
  'MobetCo',
  'Baxtiyor Oila',
  'Asr Kimyo',
  'President Gifts',
] as const;
