export const clientList = [
  'Dilmuss',
  'Bek Ota',
  'Taxtakon',
  'Aurus Pharm',
  'Ahmad Tea',
  'Baxtiyor Oila',
  'Asr Kimyo',
  'MARF',
  'Merit Chemicals',
  'Najot Nur Notiqlik Maktabi',
  'OXUS University',
  'MobetCo',
  'President Gifts',
  'Sfera',
  'Tima',
  'Zahratun Supermarket',
  "Za'faron",
  'Impuls Tibbiyot Instituti',
  'Milestone IS',
  'Damar',
  'AQLY',
] as const;
